---
# handlers file for ansible_configuration
- name: start docker
  service:
    name: docker
    state: started
    enabled: true

- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: true