---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhubauthcred
  namespace: default-backend-ns
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[...BASE64 ENCODED STRING...]



# Или создать через команду (именно так сделално в этой работе)
#
# kubectl create secret docker-registry dockerhubauthcred \
#    --docker-server=docker.io \
#    --docker-username=<your-dockerhub-username> \
#    --docker-password=<your-dockerhub-password> \
#    --docker-email=<your-email> \
#    --namespace=default-backend-ns